### ISSUE TITLE
Error in `my allocator`

### ISSUE THREAD

**Issue by S1xe** [Spdwal/StudySTL#3]
According to https://github.com/Spdwal/StudySTL/commit/4d0dc71064a8746434df40a228d6192618b14925,
there is some errors.
1.
https://github.com/Spdwal/StudySTL/blob/4d0dc71064a8746434df40a228d6192618b14925/Chapter_19/maalloc11.hpp#L17
It should be `static_cast`,but not `static`
2.
https://github.com/Spdwal/StudySTL/blob/4d0dc71064a8746434df40a228d6192618b14925/Chapter_19/maalloc11.hpp#L20
`sid::size_t` should be `std::size_t`
3.
The compare functions both remain errors.
```c++
    MyAlloc<int> p, q;
    MyAlloc<double> a, b;
    std::cout << "(p != q)" << (p != q) << std::endl; //0
    std::cout << "(p == q)" << (p == q) << std::endl; //1
    std::cout << "(a == p)" << (a == p) << std::endl; //1
    std::cout << "(a != p)" << (a != p) << std::endl; //0
```
The compare functions should be as the following code
```c++
template <typename T>
bool operator==(const MyAlloc<T> &, const MyAlloc<T> &) noexcept
{
    return true;
}
template <typename T1, typename T2>
bool operator==(const MyAlloc<T1> &, const MyAlloc<T2> &) noexcept
{
    return false;
}

template <typename T1, typename T2>
bool operator!=(const MyAlloc<T1> &a, const MyAlloc<T2> &b) noexcept
{
    return !(a == b);
}
```

**Comment by Spdwal** [comment]
emmmm..thx, I'll study for UnitCpp...
